# Generated by Django 2.2.4 on 2019-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='digest',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
