# Generated by Django 2.2.4 on 2019-08-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='digest',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
