# Generated by Django 2.2.4 on 2019-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190820_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='digest',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadtoken',
            name='token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['digest'], name='api_image_digest_3aef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadtoken',
            index=models.Index(fields=['token'], name='api_uploadt_token_55b08d_idx'),
        ),
    ]
